### ISSUE TITLE
ASP MVC 5 version?

### ISSUE THREAD

**Issue by papyr** [hey-red/Markdown#73]
Hi, can you add an ASP MVC sample on this, to show how to support it in the browser please.

thanks

**Comment by hey-red** [comment]
I don't quite understand what you want. In ASP.NET project just use example from README. 
Or needed example with razor?

**Comment by papyr** [comment]
Hi @hey-red  first great component :+1: and yes I was asking to try and get started in Razor MVC please.

**Comment by hey-red** [comment]
This non issue for md. Read razor docs(tag helpers) and use example from README.
