### ISSUE TITLE
Different behaviour for email address from MarkdownSharp

### ISSUE THREAD

**Issue by matt-richardson** [hey-red/Markdown#75]
We are looking to convert from `MarkdownSharp` to this one, and as a sanity check, I ran the `MarkdownSharp` tests against this code base, and the only difference is in the way it encodes email addresses.

Looking at the history, it appears that https://github.com/hey-red/Markdown/commit/479907fa60806b27357cbb4f4f2103612ab5022e changed the behaviour for email addresses.

The old way only handled email addresses wrapped in angle brackets, ie `<address@domain.foo>` whereas it now allows emails without the angle brackets, ie `address@domain.foo`.

Would you consider a PR to allow selection of old/new behaviour behind an option?

**Comment by matt-richardson** [comment]
Fixed by #76

**Comment by hey-red** [comment]
@matt-richardson currently by default emails autolinked only with angle brackets, 4dc3ede
Package updates will be soon.
