### ISSUE TITLE
Compatibility issues with MarkdownSharp

### ISSUE THREAD

**Issue by matt-richardson** [hey-red/Markdown#77]
There are a few other compatibility issues, but not as impacting as #75 .
1) `Transform` in the MarkdownSharp code base returns the string with a trailing `\n`, whereas this one does not.
2) `AllowEmptyLinkText` defaults to `false` whereas I think it needs to default to `true` to keep matching behaviour.

**Comment by hey-red** [comment]
1). I cant find nothing about this in md spec. There are good reasons to add it ?
2). It makes sense (but I do not like that you can create a hidden link). Create PR or I'll do it but later.

**Comment by matt-richardson** [comment]
I'm more thinking more from a in-place replacement point of view rather than whether its a good idea or not :)

If i get a chance I'll create the PR, but as there's a workaround its not as high on the priority list.

**Comment by hey-red** [comment]
@matt-richardson AllowEmptyLinkText currently = true 
61e1fa6
